### PR TITLE
create a simple RSpec matcher

### PR DESCRIPTION
**Pull request by antoniosb**
It creates a RSpec matcher to use on controller specs.

### CODE REVIEW

**Comment by antoniosb** [comment]
You can see an use case at https://github.com/appprova/appprova/pull/588

**Comment by taiar** [comment]
:+1: so cool!

**Comment by joaofraga** [comment]
Nice :+1:

**Comment by LeandroLM** [comment]
:+1:

**Comment by tlluiz** [comment]
👍

**Pull request merged**
