### PR TITLE
Support for rails 4

### PR DESCRIPTION
**Pull request by martinstiago**
Supporting Rails 4 applications.

### CODE REVIEW

**Comment by joaofraga** [comment]
I think this way you're removing the compatibility with rails 3.*. What do you think to remove the rails and activesupport min versions?

**Comment by martinstiago** [comment]
@joaofraga So, how you manage to do that, and maintain the regular behavior? The versions 0.1.\* will keep the support for rails 3.*.

I guess that your suggestion is a matter to a new PR, don't you think? If so, you are more than welcome to do it! ;)

**Comment by joaofraga** [comment]
@MartinsTiago I can't agree with that. You're breaking backward compatibility with already in production versions of action_tracker. I think what you can do to achieve this is removing the versions requirement and allow the application to install the needed versions.

Is good to remember, action_tracker is not a standalone library and does not work without the rails application, which already comes with rails and activesupport gems.

**Comment by martinstiago** [comment]
@joaofraga Yep, you're right, it just don't need the version lock.

**Comment by LeandroLM** [comment]
:+1:

**Comment by taiar** [comment]
@MartinsTiago @joaofraga @LeandroLM are you aware that open-ended dependency versions will cause warnings when building the gem, right?

```
# taiar at app-prova-taiar in ~/dev/action_tracker on git:feature/rails-4-support ✖︎ [13:33:58]
→ gem build action_tracker.gemspec 
WARNING:  open-ended dependency on activesupport (>= 0) is not recommended
  if activesupport is semantically versioned, use:
    add_runtime_dependency 'activesupport', '~> 0'
WARNING:  open-ended dependency on rails (>= 0, development) is not recommended
  if rails is semantically versioned, use:
    add_development_dependency 'rails', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: action_tracker
  Version: 0.1.6.3
  File: action_tracker-0.1.6.3.gem
```

**Comment by joaofraga** [comment]
@MartinsTiago take a look at how Paperclip do that: https://github.com/thoughtbot/paperclip/blob/master/paperclip.gemspec

**Comment by martinstiago** [comment]
@taiar @joaofraga Just removed the open dependency warnings.

**Comment by taiar** [comment]
Good job. :+1:

**Comment by joaofraga** [comment]
:+1:

**Pull request closed without merging**
